### ISSUE TITLE
WKT to Geojson?

### ISSUE THREAD

**Issue by stefanocudini** [oliverroick/Geojson2Wkt#5]
Would it be feasible to implement the inverse functions? using the same code in part?

**Comment by oliverroick** [comment]
Hi Stefano, 

Thanks for reaching out. This is something I have considered before but then there's [Terraformer](https://github.com/Esri/terraformer), which has a [decent solution](http://terraformer.io/wkt-parser/) for converting WKT to GeoJSON.

**Comment by stefanocudini** [comment]
many thanks... I'm just found [wkx](https://www.npmjs.com/package/wkx)
